var products = [
  {
    name: "Scorpio Galaxy",
    id: 1,
    thumb: require("./assets/images/1.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Letter E",
    id: 2,
    thumb: require("./assets/images/2.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Squid Games 1",
    id: 3,
    thumb: require("./assets/images/3.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "French Stripes 1",
    id: 4,
    thumb: require("./assets/images/4.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "French Stripes 2",
    id: 5,
    thumb: require("./assets/images/5.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "French Stripes 3",
    id: 6,
    thumb: require("./assets/images/6.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Squid Games 2",
    id: 7,
    thumb: require("./assets/images/7.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Duo Tone 1",
    id: 8,
    thumb: require("./assets/images/8.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Duo Tone 2",
    id: 9,
    thumb: require("./assets/images/9.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Duo Tone 3",
    id: 10,
    thumb: require("./assets/images/10.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Squid Games 3",
    id: 11,
    thumb: require("./assets/images/11.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Squid Games 4",
    id: 12,
    thumb: require("./assets/images/12.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Flower Pot",
    id: 13,
    thumb: require("./assets/images/13.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Green Plus",
    id: 14,
    thumb: require("./assets/images/14.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 1",
    id: 15,
    thumb: require("./assets/images/15.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 2",
    id: 16,
    thumb: require("./assets/images/16.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Woman in Cup",
    id: 17,
    thumb: require("./assets/images/17.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 3",
    id: 18,
    thumb: require("./assets/images/18.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 4",
    id: 19,
    thumb: require("./assets/images/19.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 5",
    id: 20,
    thumb: require("./assets/images/20.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 6",
    id: 21,
    thumb: require("./assets/images/21.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Gemini Galaxy",
    id: 22,
    thumb: require("./assets/images/22.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Clouds 1",
    id: 23,
    thumb: require("./assets/images/23.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Clouds 2",
    id: 24,
    thumb: require("./assets/images/24.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Clouds 3",
    id: 25,
    thumb: require("./assets/images/25.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Clouds 4",
    id: 26,
    thumb: require("./assets/images/26.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Clouds 5",
    id: 27,
    thumb: require("./assets/images/27.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Green Leaves",
    id: 28,
    thumb: require("./assets/images/28.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Hello Flower",
    id: 29,
    thumb: require("./assets/images/29.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Flower",
    id: 30,
    thumb: require("./assets/images/30.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Flower Art",
    id: 31,
    thumb: require("./assets/images/31.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Be(e) Kind",
    id: 32,
    thumb: require("./assets/images/32.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Love and Pizza",
    id: 33,
    thumb: require("./assets/images/33.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Butterflies",
    id: 34,
    thumb: require("./assets/images/34.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Be Okay",
    id: 35,
    thumb: require("./assets/images/35.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Beautiful Person",
    id: 36,
    thumb: require("./assets/images/36.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Strawberry Day",
    id: 37,
    thumb: require("./assets/images/37.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Get a Dog",
    id: 38,
    thumb: require("./assets/images/38.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "White Flowers",
    id: 39,
    thumb: require("./assets/images/39.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Flower 2",
    id: 40,
    thumb: require("./assets/images/40.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Happy",
    id: 41,
    thumb: require("./assets/images/41.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Letter A",
    id: 42,
    thumb: require("./assets/images/42.jpg"),
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
];

var smartphones = {
  iPhone: [
    "13 Pro Max",
    "13 Pro",
    "13",
    "13 Mini",
    "12 Pro Max",
    "12 / 12 Pro",
    "12 Mini",
    "11 Pro Max",
    "11 Pro",
    "11",
    "XS Max",
    "XR",
    "X / XS",
    "6 Plus / 7 Plus / 8 Plus",
    "7 / 8 / SE(2020)",
    "6 / 6 S",
  ],
  Samsung: [
    "S21 Ultra",
    "S21 FE",
    "S21 Plus",
    "S21",
    "A52 5G",
    "A42 5G",
    "S20 FE",
    "S20 Ultra",
    "S20 Plus",
    "S20",
    "S10",
    "S10 Plus",
    "S10e",
    "S9",
    "S8",
  ],
  Pixel: ["6 Pro", "6", "5a 5G", "5", "4a 5G", "4a", "4XL", "3a"],
};

var cart = [];

export default products;
export { smartphones, cart };